### ISSUE TITLE
HTML and images

### ISSUE THREAD

**Issue by zosocanuck** [OpenESignForms/openesignforms#167]
Hi,

I'm attempting to display an image uploaded to OpenESF via the following div class:

`<div id="dimg1"><img id="img1" src="xyz.jpg" /></div>`

Can anyone point to the proper way of doing this

**Comment by OpenESignForms** [comment]
Note that you are posting to the issues tracker rather than the forum, which may be more suited to simple questions: https://groups.google.com/forum/#!forum/openesignformsdev

We try to reserve git issues for bug reports and enhancement requests.

With OpenESF, you need to define a "file upload" field (called "imageFile" here) in your document and reference in the HTML as ${imageFile} or the like.
