### ISSUE TITLE
Any option for adding payment gateways.

### ISSUE THREAD

**Issue by nik10-mah** [OpenESignForms/openesignforms#174]
Is there a way for any option for payments. For example, I want to commercialize it so that the clients using my openesf hosted application pay after certain period of trial time.?

**Comment by OpenESignForms** [comment]
We prefer if you'd ask basic questions in our forum (https://groups.google.com/forum/#!forum/openesignformsdev) rather than issues as few look to the issues except for bugs/enhancements.  We prefer to try to work out items via the forum, and use the issues when there's a request to fix or add features.

That said, no there's no built-in metering for charging people to use open source code.  There's no billing whatsoever.  There is a "license type" field we have for deployments, so perhaps it could be extended to allow for "a time-license" or the like, but again, no metering itself is built in (this is just an attribute value and has no practical issue for enforcing a usage or payment).

**Comment by OpenESignForms** [comment]
No further responses so we'll assume this is closed.

A quick comment is that it would be easy to provide a service built on OpenESF in which you give the a trial period at no cost (or whatever your biz model is) and then bill them afterwards.  Pretty much all trial usage is done like that rather than the software itself knowing details about your business model.  We sell commercial license as pre-paid in full, annual subscriptions, monthly subscriptions, reseller rates, open source, etc. and these are all external to OpenESF itself.  You can even ensure your documents contain a "Free Trial" message that you remove once they are start paying.  Good luck!
