### ISSUE TITLE
Intermittent rendering of variable values in email templates

### ISSUE THREAD

**Issue by blairbenjamin** [OpenESignForms/openesignforms#184]
I'm using some built-in field values in email templates and getting inconsistent results.  Sometimes it shows the value and other times it shows the field name.  Below are screen shots from two emails sent as part of the same transaction using the same email template.  On one it showed the value and on the other it instead rendered the field name.  Why might this be?
![variables1](https://user-images.githubusercontent.com/65978479/82944025-82e9d880-9f68-11ea-9122-89446bd63645.png)

![variables2](https://user-images.githubusercontent.com/65978479/82944047-8b421380-9f68-11ea-8859-3fd5168f4f0d.png)

**Comment by OpenESignForms** [comment]
We're not using github much these days, so it's better to post on google groups (https://groups.google.com/forum/#!forum/yozonsesignforms) or email support directly.

That said, built-ins may vary in behavior for some items because when the email is sent, it may not have a concept of "user" anymore.  Better is to build a document field to hold these values while the transaction is in process by the user.  Then your email template can reference that more stable field value.
