### ISSUE TITLE
Mechanism to REJECT, send back to a previous party

### ISSUE THREAD

**Issue by GoogleCodeExporter** [OpenESignForms/openesignforms#98]
```
Looking for a way to allow a party to REJECT a document (or perhaps more nicely 
stated as "request corrections or changes") such that when the party completes, 
the transaction is sent back to the previous (or other) party for fixes, 
changes, etc.

This is used in "negotiation" style contracts in which terms are being worked 
on, and rather than signing, the party wants a change to be made first.

It is also used in classic approve/reject scenarios where a party may find 
errors or the like that need to be corrected before moving forward.

Today, this can be done perhaps using custom logic and special fields to 
trigger changes in the flow, but would like a more straightforward way to set 
this up to handle typical needs in a clear way.
```

Original issue reported on code.google.com by `yoz...@gmail.com` on 30 Apr 2013 at 10:53

**Comment by OpenESignForms** [comment]
Custom logic is still the best bet for this as there are so many alternatives it's hard to create a single setup to handle it all.  That is, will you want to blank out signature fields for a prior party when returning to them?  Do you need to reject back multiple parties, and if so, do the other parties in between also get reset?  Do emails need to be sent out?

**Comment by OpenESignForms** [comment]
As of release 19.1.19:
Added new "redo party" statuses.  The custom logic action 'Change tran/party status' now includes 'Redo party' (to have a prior completed party redo all their documents) and 'Redo document party' (to have a completed party redo a specified set of documents).  Added ${transaction:party.redodatetime} (the date+time the party was setup for 'redo') and ${transaction:party.isredo} ("true" if the party is redoing work, "false" otherwise), as well as the Java JSP interface esf.isPartyMarkedForRedo() and esf.getPartyMarkedForRedoDateTime() to control this via advanced JSP programming in your document. The package party setup now includes a second, optional email template specification to use for notifying a party when requested to redo their work.
